server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true #是否将自己的Ip注册到eureka种，默认false 注册 主机名
    ip-address: 127.0.0.1 #设置当前实例ip
    #instance-id: 修改instance-id显示
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30 #每一次eureka client 先eureka server发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 90 #如果90秒 eureka -server 没有eureka client 发送心跳包 注册书中删除注册

  client:
    service-url:
      defaultZonezz: http://localhost:8761/eureka #,http://eureka-server1:8763/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
    register-with-eureka: true #启动时是否将自己注册到eureka上
    fetch-registry: true  #是否需要从eureka种抓取数据


spring:
  application:
    name: eureka-provider #设置当前应用名称


ydlclass: itymh
